CREATE DATABASE CLIENTEDB;
GO
USE [CLIENTEDB];
GO
CREATE TABLE Clientes
(
	Id INT IDENTITY ( 1, 1) NOT NULL,
	Nome VARCHAR(300) NOT NULL,
	CPF VARCHAR(15) NOT NULL,
	DataNascimento DATETIME NOT NULL,
	Genero CHAR(1) NOT NULL,

	CONSTRAINT PK_Cliente PRIMARY KEY (Id),
	CONSTRAINT CH_Cliente CHECK (Genero IN('M', 'F'))
);
GO
CREATE TABLE Telefones
(
	Id INT IDENTITY ( 1, 1),
	DDD VARCHAR(5) NOT NULL,
	Numero VARCHAR(10) NOT NULL,
	IdCliente INT NOT NULL,

	CONSTRAINT PK_Telefone PRIMARY KEY (Id),
	CONSTRAINT FK_Telefone FOREIGN KEY (IdCliente) REFERENCES Clientes (Id)
	
);
